### Empty arrays

In [1]:
import numpy as np

#### Zeros

In [6]:
vector = np.zeros(5) # Vector de 5 ceros decimales
print(vector)
print()

matriz = np.zeros((3,4)) # Matriz de 3 filas y 4 columnas de ceros decimales
print(matriz)

print()
print(matriz[1,1])

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

0.0


##### Ones

In [7]:
vector = np.ones(5) # Vector de 5 números uno decimales
print(vector)
print()

matriz = np.ones((3,4)) # Matriz de 3 filas y 4 columnas de números uno decimales
print(matriz)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
